"use client";
import * as React from "react";
import { Printer, Download, FlaskConical, Building2, Handshake, TrendingUp, AlertTriangle } from "lucide-react";
import { Card, CardBody, Button, Pill, LevelBadge, MomentumBadge, MeterBar, DemoBadge } from "@/components/ui";
import { EvidenceDrawer } from "@/components/intelligence/evidence-drawer";
import { mineralName, technologyName, orgName, STAGE_SHORT } from "@/lib/data";
import { formatPercent } from "@/lib/utils";
import type { PolicyBrief } from "./build-brief";

function EvidenceChip({ ids, label, onOpen }: { ids: string[]; label?: string; onOpen: (ids: string[]) => void }) {
  if (ids.length === 0) return null;
  return (
    <button
      type="button"
      onClick={() => onOpen(ids)}
      className="inline-flex items-center gap-1 rounded-full border border-data/30 bg-data/10 px-2 py-0.5 text-2xs font-medium text-data transition-colors hover:bg-data/20"
    >
      <FlaskConical className="h-3 w-3" /> {label ?? `Evidence (${ids.length})`}
    </button>
  );
}

function SectionTitle({ icon: Icon, children }: { icon: React.ComponentType<{ className?: string }>; children: React.ReactNode }) {
  return (
    <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-ink">
      <Icon className="h-4 w-4 text-mineral" /> {children}
    </h3>
  );
}

function downloadJSON(brief: PolicyBrief) {
  const payload = {
    generatedAt: brief.generatedAt,
    mineral: brief.mineral.name,
    params: brief.params,
    executiveSummary: brief.executiveSummary,
    technologyLandscape: brief.technologyLandscape.map((t) => ({
      id: t.id,
      name: t.name,
      maturity: t.maturity,
      momentum: t.momentum,
    })),
    indiaCapability: brief.indiaCapability,
    globalActivity: brief.globalActivity,
    emergingTechnologies: brief.emergingTechnologies.map((e) => ({
      technology: technologyName(e.technology),
      zone: e.zone,
      momentum: e.momentum,
      emergingScore: e.emergingScore,
    })),
    gapSignals: brief.gapSignals.map((g) => ({
      technology: technologyName(g.technology),
      gapType: g.gapType,
      confidence: g.confidence,
      evidenceSufficiency: g.evidenceSufficiency,
      dataLimitations: g.dataLimitations,
      evidenceIds: g.evidenceIds,
    })),
    leadingOrganisations: brief.leadingOrganisations.map((o) => ({ name: o.name, type: o.type, country: o.country })),
    collaborationSignals: brief.collaborationSignals.map((c) => ({
      orgA: orgName(c.orgA),
      orgB: orgName(c.orgB),
      complementarity: c.complementarity,
      rationale: c.rationale,
    })),
    evidenceCount: brief.evidenceCount,
    evidenceSampleIds: brief.evidenceSampleIds,
    dataLimitations: brief.dataLimitations,
    footer: "Generated by KhanijDrishti · Evidence-backed prototype intelligence",
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `khanijdrishti-brief-${brief.mineral.id}-${brief.params.fromYear}-${brief.params.toYear}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Structured, evidence-linked policy brief report card (spec §45). */
export function BriefReport({ brief }: { brief: PolicyBrief }) {
  const [drawerIds, setDrawerIds] = React.useState<string[] | null>(null);
  const stages = Object.entries(brief.indiaCapability.avgByStage) as [string, number][];

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-end gap-2 print:hidden">
        <Button variant="outline" size="sm" onClick={() => window.print()}>
          <Printer className="h-3.5 w-3.5" /> Export PDF
        </Button>
        <Button variant="secondary" size="sm" onClick={() => downloadJSON(brief)}>
          <Download className="h-3.5 w-3.5" /> Export JSON
        </Button>
      </div>

      <Card className="print:border-black/20 print:bg-white print:text-black">
        <CardBody className="space-y-8">
          <header className="flex flex-wrap items-start justify-between gap-3 border-b border-border pb-4">
            <div>
              <div className="font-mono text-2xs uppercase tracking-[0.18em] text-mineral">Intelligence Brief</div>
              <h2 className="mt-1 text-xl font-semibold text-ink print:text-black">
                {mineralName(brief.params.mineralId)} — {brief.technologyLabel}
              </h2>
              <p className="mt-1 text-2xs text-ink-faint">
                {brief.params.fromYear}–{brief.params.toYear} · {brief.params.geography} · Audience: {brief.params.audience} ·
                generated {new Date(brief.generatedAt).toLocaleString("en-IN")}
              </p>
            </div>
            <DemoBadge />
          </header>

          <section>
            <SectionTitle icon={FlaskConical}>Executive Summary</SectionTitle>
            <p className="text-sm leading-relaxed text-ink-soft">{brief.executiveSummary}</p>
          </section>

          <section>
            <SectionTitle icon={TrendingUp}>Technology Landscape</SectionTitle>
            {brief.technologyLandscape.length === 0 ? (
              <p className="text-sm text-ink-faint">No tracked technologies match this selection.</p>
            ) : (
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                {brief.technologyLandscape.map((t) => (
                  <div key={t.id} className="rounded-md border border-border bg-surface-2 p-3">
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-sm font-medium text-ink">{t.name}</span>
                      <MomentumBadge value={t.momentum} />
                    </div>
                    <p className="mt-1 text-2xs text-ink-faint">{t.description}</p>
                    <div className="mt-2 flex flex-wrap gap-1.5 text-2xs text-ink-faint">
                      <Pill className="border-border-strong bg-surface text-ink-soft">{t.maturity}</Pill>
                      <span>{t.metrics.patentFamilies} patent families</span>
                      <span>· {t.metrics.publications} publications</span>
                      <span>· {t.metrics.rdProjects} R&D projects</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>

          <section>
            <SectionTitle icon={Building2}>India Capability</SectionTitle>
            <p className="mb-2 text-2xs text-ink-faint">
              Average domestic capability score by value-chain stage, aggregated across {brief.indiaCapability.orgCount}{" "}
              organisation{brief.indiaCapability.orgCount === 1 ? "" : "s"} active on this mineral (demo heuristic, 0–1).
            </p>
            {stages.length === 0 ? (
              <p className="text-sm text-ink-faint">No organisation capability data available for this selection.</p>
            ) : (
              <div className="space-y-2">
                {stages.map(([stage, v]) => (
                  <MeterBar key={stage} value={v} label={STAGE_SHORT[stage as keyof typeof STAGE_SHORT] ?? stage} valueLabel={formatPercent(v)} tone="mineral" />
                ))}
              </div>
            )}
          </section>

          <section>
            <SectionTitle icon={TrendingUp}>Global Activity</SectionTitle>
            <p className="mb-2 text-2xs text-ink-faint">{brief.globalActivity.note}</p>
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-3">
              <MeterBar value={brief.globalActivity.indiaSharePatents} label="India share of patents" valueLabel={formatPercent(brief.globalActivity.indiaSharePatents)} tone="data" />
              <MeterBar value={brief.globalActivity.indiaShareRd} label="India share of R&D" valueLabel={formatPercent(brief.globalActivity.indiaShareRd)} tone="data" />
              <MeterBar value={brief.globalActivity.indiaSharePublications} label="India share of publications" valueLabel={formatPercent(brief.globalActivity.indiaSharePublications)} tone="data" />
            </div>
          </section>

          <section>
            <SectionTitle icon={TrendingUp}>Emerging Technologies</SectionTitle>
            {brief.emergingTechnologies.length === 0 ? (
              <p className="text-sm text-ink-faint">No emerging-technology signal tracked for this selection.</p>
            ) : (
              <div className="space-y-2">
                {brief.emergingTechnologies.map((e) => (
                  <div key={e.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-border bg-surface-2 px-3 py-2">
                    <span className="text-sm text-ink">{technologyName(e.technology)}</span>
                    <div className="flex items-center gap-2 text-2xs text-ink-faint">
                      <Pill className="border-border-strong bg-surface text-ink-soft">{e.zone}</Pill>
                      <MomentumBadge value={e.momentum} />
                      <span>score {(e.emergingScore * 100).toFixed(0)}%</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>

          <section>
            <SectionTitle icon={AlertTriangle}>Potential Gap Signals</SectionTitle>
            {brief.gapSignals.length === 0 ? (
              <p className="text-sm text-ink-faint">No Potential Capability Gap Signal identified for this selection.</p>
            ) : (
              <div className="space-y-2">
                {brief.gapSignals.map((g) => (
                  <div key={g.id} className="rounded-md border border-border bg-surface-2 p-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span className="text-sm font-medium text-ink">
                        {technologyName(g.technology)} — <span className="text-ink-soft">{g.gapType}</span>
                      </span>
                      <div className="flex items-center gap-2">
                        <LevelBadge value={g.confidence} label="Confidence" />
                        <LevelBadge value={g.evidenceSufficiency} label="Evidence sufficiency" />
                      </div>
                    </div>
                    <p className="mt-1.5 text-2xs text-ink-faint">{g.dataLimitations}</p>
                    <div className="mt-2">
                      <EvidenceChip ids={g.evidenceIds} onOpen={setDrawerIds} />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>

          <section>
            <SectionTitle icon={Building2}>Leading Organisations</SectionTitle>
            {brief.leadingOrganisations.length === 0 ? (
              <p className="text-sm text-ink-faint">No organisations found for this selection.</p>
            ) : (
              <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                {brief.leadingOrganisations.map((o) => (
                  <div key={o.id} className="rounded-md border border-border bg-surface-2 p-3">
                    <div className="text-sm font-medium text-ink">{o.name}</div>
                    <div className="mt-0.5 text-2xs text-ink-faint">
                      {o.type} · {o.country} · {o.metrics.patentFamilies} patents · {o.metrics.publications} publications
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>

          <section>
            <SectionTitle icon={Handshake}>Collaboration Signals</SectionTitle>
            {brief.collaborationSignals.length === 0 ? (
              <p className="text-sm text-ink-faint">No Potential Complementary Capability Signal identified for this mineral.</p>
            ) : (
              <div className="space-y-2">
                {brief.collaborationSignals.map((c) => (
                  <div key={c.id} className="rounded-md border border-border bg-surface-2 p-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span className="text-sm text-ink">
                        {orgName(c.orgA)} <span className="text-ink-faint">×</span> {orgName(c.orgB)}
                      </span>
                      <span className="text-2xs text-ink-faint">complementarity {(c.complementarity * 100).toFixed(0)}%</span>
                    </div>
                    <p className="mt-1 text-2xs text-ink-faint">{c.rationale}</p>
                    <div className="mt-2">
                      <EvidenceChip ids={c.evidenceIds} onOpen={setDrawerIds} />
                    </div>
                  </div>
                ))}
              </div>
            )}
          </section>

          <section>
            <SectionTitle icon={FlaskConical}>Evidence</SectionTitle>
            <p className="mb-2 text-sm text-ink-soft">
              {brief.evidenceCount} evidence record{brief.evidenceCount === 1 ? "" : "s"} in the indexed demo dataset
              support this brief.
            </p>
            <div className="flex flex-wrap gap-1.5">
              {brief.evidenceSampleIds.map((id) => (
                <EvidenceChip key={id} ids={[id]} label={id} onOpen={setDrawerIds} />
              ))}
            </div>
          </section>

          <section>
            <SectionTitle icon={AlertTriangle}>Data Limitations</SectionTitle>
            <ul className="list-disc space-y-1 pl-5 text-2xs text-ink-faint">
              {brief.dataLimitations.map((d) => (
                <li key={d}>{d}</li>
              ))}
            </ul>
          </section>

          <footer className="border-t border-border pt-4 text-2xs text-ink-faint">
            Generated by KhanijDrishti · Evidence-backed prototype intelligence
          </footer>
        </CardBody>
      </Card>

      <EvidenceDrawer open={!!drawerIds} onClose={() => setDrawerIds(null)} evidenceIds={drawerIds ?? []} />
    </div>
  );
}
